const languages = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  ja: "日本語",
  pt: "Português",
  it: "Italiano",
  "zh-CN": "中文 (简体)",
  "zh-TW": "中文 (繁體)",
  ar: "العربية",
  ru: "Русский",
  ko: "한국어",
  hi: "हिन्दी",
  id: "Bahasa Indonesia",
  pl: "Polski",
  nl: "Nederlands",
  sv: "Svenska",
  th: "ภาษาไทย",
  iw: "עברית",
  vi: "Tiếng Việt",
  cs: "Čeština",
  uk: "Українська",
  ro: "Română",
  el: "Ελληνικά",
  tr: "Türkçe",
};